#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/wxprec.h>
#include <wx/dcbuffer.h>
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel3OnUpdateUI( wxUpdateUIEvent& event );
		void m_panel4OnUpdateUI( wxUpdateUIEvent& event );
		void m_panel5OnUpdateUI( wxUpdateUIEvent& event );
		void m_button1OnButtonClick( wxCommandEvent& event );
		void m_slider1OnScroll( wxScrollEvent& event );
		void m_slider2OnScroll( wxScrollEvent& event );
		void m_slider3OnScroll( wxScrollEvent& event );
		void m_slider4OnScroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		wxImage MyImage;
		wxBitmap MyBitmap;

		void DrawPicture(wxPaintEvent& e);






};

#endif // __GUIMyFrame1__
